blacklist:
  - DIAMOND
  - DIAMOND_BLOCK

commands:
  sell:
    permission-required: true
    permission-node: "market.sell"
  cost:
    permission-required: false
    permission-node: "market.cost"
  buy:
    permission-required: false
    permission-node: "market.buy"
