enable-plugin: true

commands:
  sell:
    permission-required: true
    permission-node: "market.sell"
  cost:
    permission-required: false
    permission-node: "market.cost"
  buy:
    permission-required: false
    permission-node: "market.buy"

blacklist: # Items that can't be sold on market
  - DIAMOND
  - DIAMOND_BLOCK

database-info: # Database info
  enabled: false
  host: "localhost"
  port: "3306"
  database: "marketdata"
  username: "root"
  password: "admin"

messages:
  prefix: "&e[Market] "
  no-sell-permission: "&fYou don't have permission to sell on market!"
  not-enough-arguments: "&fYou haven't entered enough arguments!"
  improper-item-number-count: "&fYou didn't input count number correctly!"
  improper-item-name: "&fYou didn't input name of item to sell correctly!"

max-price: 128 # Default max price for all items in diamonds(automatically calculated for diamond_blocks)

price: # Min and max prices of items in diamonds(it is calculated automatically for diamond_blocks)
  EXAMPLE1: # Item name
    min: 2 # Min price can't be smaller than 1
    max: 5 # Max price can be bigger than default max price
  EXAMPLE2:
    max: 3 # You can also only put min or max