enable-plugin: true

blacklist:
  - DIAMOND
  - DIAMOND_BLOCK

commands:
  sell:
    permission-required: true
    permission-node: "market.sell"
  cost:
    permission-required: false
    permission-node: "market.cost"
  buy:
    permission-required: false
    permission-node: "market.buy"

max-price: 128 # Default max price for all items in diamonds(automatically calculated for diamond_blocks)

price: # Min and max prices of items in diamonds(it is calculated automatically for diamond_blocks)
  EXAMPLE1: # Item name
    min: 2 # Min price can't be smaller than 1
    max: 5 # Max price can be bigger than default max price
  EXAMPLE2:
    max: 3 # You can also only put min or max