name: Market
version: 0.4.2
author: Tuce
main: me.tuce.firstplugin.Main
api-version: 1.17
commands:
  sell:
    description: Puts item on sale in full stacks
    usage: /<command> [CountOfStacks] [ItemName] [Cost] [diamond/diamond_block](default diamond)
  sellhstack:
    description: Puts item on sale in half stacks
    usage: /<command> [CountOfHStacks] [ItemName] [Cost] [diamond/diamond_block](default diamond)
  cost:
    description: Shows the least expensive item on sale
    usage: /<command> [ItemName]
  buy:
    description: Buys the least expensive item on sale
    usage: /<command> [CountOfItem] [ItemName] [stack/halfstack](default stack)
