name: Market
version: 0.6.0
author: Tuce
main: me.tuce.firstplugin.Main
api-version: 1.17
commands:
  msell:
    description: Puts item on sale in full stacks
    usage: /<command> [CountOfStacks] [ItemName] [Cost] [diamond/diamond_block](default diamond)
  msellhalfstack:
    description: Puts item on sale in half stacks
    usage: /<command> [CountOfHalfStacks] [ItemName] [Cost] [diamond/diamond_block](default diamond)
  mcost:
    description: Shows the least expensive item on sale
    usage: /<command> [ItemName]
  mbuy:
    description: Buys the least expensive item on sale
    usage: /<command> [CountOfItem] [ItemName] [stack/halfstack](default stack)
  mcollect:
    description: Collect diamonds from transactions that happened while you were offline
    usage: /<command>
  myes:
    description: Confirm that you want to buy/sell
    usage: /<command>
  mno:
    description: Confirm that you don't want to buy/sell
    usage: /<command>
